# GeoPandas Basics

## Overview
GeoPandas extends pandas with a `geometry` column and spatial operations powered by Shapely, Fiona, and PyProj. It is the standard Python tool for working with vector spatial data.

**Core objects:**
```python
import geopandas as gpd

gdf = gpd.GeoDataFrame(data, geometry=[Point(-66,46), ...], crs='EPSG:4326')
gdf.crs                     # CRS of the GeoDataFrame
gdf.to_crs('EPSG:32620')    # reproject
gdf.geometry.distance(pt)   # element-wise distance
gdf.geometry.buffer(1000)   # 1000-unit buffer
gpd.sjoin(a, b, predicate='within')  # spatial join
gpd.overlay(a, b, how='intersection')  # spatial overlay
```

**Install:**
```bash
pip install geopandas shapely pyproj fiona
```

---

In [1]:
import geopandas as gpd
import pandas as pd
from shapely.geometry import Point, Polygon, LineString, MultiPolygon
import pyproj

# ── Ecological dataset: Atlantic Canada ───────────────────────────
# Monitoring sites, species observations, protected areas, watersheds

# Monitoring sites (water quality / biodiversity)
sites_data = {
    'site_id':   ['S01','S02','S03','S04','S05','S06','S07','S08'],
    'site_name': ['Petitcodiac River','Miramichi Lake','Fundy Shore',
                  'Tantramar Marsh','Kouchibouguac','Restigouche River',
                  'Saint John River','Annapolis Valley'],
    'province':  ['NB','NB','NB','NB','NB','NB','NB','NS'],
    'elevation_m':[12, 84, 5, 3, 8, 45, 18, 62],
    'geometry':  [
        Point(-64.96, 46.07), Point(-66.18, 46.85), Point(-65.07, 45.55),
        Point(-64.40, 45.90), Point(-64.95, 46.82), Point(-67.60, 47.70),
        Point(-66.64, 45.95), Point(-65.12, 45.05),
    ],
}
sites = gpd.GeoDataFrame(sites_data, crs='EPSG:4326')

# Protected areas (simplified polygons)
prot_data = {
    'pa_id':    ['PA01','PA02','PA03'],
    'name':     ['Fundy National Park','Kouchibouguac NP','Kejimkujik NP'],
    'type':     ['National Park','National Park','National Park'],
    'area_km2': [207, 239, 404],
    'geometry': [
        Polygon([(-65.4,45.4),(-64.6,45.4),(-64.6,45.7),(-65.4,45.7)]),
        Polygon([(-64.9,46.6),(-64.7,46.6),(-64.7,47.0),(-64.9,47.0)]),
        Polygon([(-65.4,44.5),(-64.8,44.5),(-64.8,44.9),(-65.4,44.9)]),
    ],
}
protected = gpd.GeoDataFrame(prot_data, crs='EPSG:4326')

# Watersheds
ws_data = {
    'ws_id':   ['WS01','WS02','WS03'],
    'name':    ['Saint John Watershed','Miramichi Watershed','Petitcodiac Watershed'],
    'area_km2':[55200, 13800, 3100],
    'geometry':[
        Polygon([(-68.0,46.8),(-66.0,46.8),(-66.0,45.0),(-68.0,45.0)]),
        Polygon([(-66.5,47.5),(-65.5,47.5),(-65.5,46.5),(-66.5,46.5)]),
        Polygon([(-65.2,46.3),(-64.5,46.3),(-64.5,45.7),(-65.2,45.7)]),
    ],
}
watersheds = gpd.GeoDataFrame(ws_data, crs='EPSG:4326')

# Species observations
obs_data = {
    'obs_id':   range(1, 11),
    'species':  ['Atlantic Salmon','Atlantic Salmon','Blanding\'s Turtle',
                 'Piping Plover','Piping Plover','Blanding\'s Turtle',
                 'Atlantic Salmon','Little Brown Bat','Little Brown Bat','Piping Plover'],
    'year':     [2022,2023,2022,2023,2022,2023,2021,2023,2022,2021],
    'count':    [12, 8, 3, 1, 2, 1, 15, 47, 52, 3],
    'geometry': [
        Point(-64.96,46.07), Point(-67.60,47.70), Point(-64.40,45.90),
        Point(-65.07,45.55), Point(-64.95,46.82), Point(-66.18,46.85),
        Point(-66.64,45.95), Point(-66.18,46.85), Point(-64.96,46.07),
        Point(-64.40,45.90),
    ],
}
observations = gpd.GeoDataFrame(obs_data, crs='EPSG:4326')

print("Ecological dataset loaded:")
for name, gdf in [('sites',sites),('protected_areas',protected),
                  ('watersheds',watersheds),('observations',observations)]:
    print(f"  {name:<18s}: {len(gdf)} features, CRS={gdf.crs.to_epsg()}")


import geopandas as gpd
import pandas as pd
from shapely.geometry import Point
import pyproj

print("=== GeoDataFrame: the geopandas core object ===")
print()

# GeoDataFrame is a pandas DataFrame with a geometry column
print(f"sites GeoDataFrame:")
print(f"  type:    {type(sites)}")
print(f"  shape:   {sites.shape}")
print(f"  CRS:     {sites.crs}")
print(f"  columns: {list(sites.columns)}")
print()
print(sites[['site_id','site_name','province','elevation_m']].to_string(index=False))

print()
# CRS operations
print("=== CRS operations ===")
print(f"  sites.crs:              {sites.crs}")
print(f"  sites.crs.to_epsg():    {sites.crs.to_epsg()}")
sites_utm = sites.to_crs("EPSG:32620")
print(f"  to_crs('EPSG:32620'):   {sites_utm.crs}")
print(f"  First site (WGS84):  {sites.geometry.iloc[0].wkt}")
print(f"  First site (UTM):    {sites_utm.geometry.iloc[0].wkt[:40]}...")

print()
# Geometry accessors
print("=== Geometry accessors (.geometry, .geom_type, .bounds) ===")
print(f"  geom_type:  {sites.geometry.geom_type.unique().tolist()}")
print(f"  bounds:\n{sites.total_bounds}")   # [minx, miny, maxx, maxy]
print()
print(f"  sites.geometry.x (longitude):\n{sites.geometry.x.round(3).tolist()}")
print(f"  sites.geometry.y (latitude):\n{sites.geometry.y.round(3).tolist()}")


Ecological dataset loaded:
  sites             : 8 features, CRS=4326
  protected_areas   : 3 features, CRS=4326
  watersheds        : 3 features, CRS=4326
  observations      : 10 features, CRS=4326
=== GeoDataFrame: the geopandas core object ===

sites GeoDataFrame:
  type:    <class 'geopandas.geodataframe.GeoDataFrame'>
  shape:   (8, 5)
  CRS:     EPSG:4326
  columns: ['site_id', 'site_name', 'province', 'elevation_m', 'geometry']

site_id         site_name province  elevation_m
    S01 Petitcodiac River       NB           12
    S02    Miramichi Lake       NB           84
    S03       Fundy Shore       NB            5
    S04   Tantramar Marsh       NB            3
    S05     Kouchibouguac       NB            8
    S06 Restigouche River       NB           45
    S07  Saint John River       NB           18
    S08  Annapolis Valley       NS           62

=== CRS operations ===
  sites.crs:              EPSG:4326
  sites.crs.to_epsg():    4326
  to_crs('EPSG:32620'):   EPSG:32620

---
## Spatial operations

In [3]:
import geopandas as gpd
import pandas as pd
from shapely.geometry import Point, Polygon, LineString, MultiPolygon
import pyproj

# ── Ecological dataset: Atlantic Canada ───────────────────────────
# Monitoring sites, species observations, protected areas, watersheds

# Monitoring sites (water quality / biodiversity)
sites_data = {
    'site_id':   ['S01','S02','S03','S04','S05','S06','S07','S08'],
    'site_name': ['Petitcodiac River','Miramichi Lake','Fundy Shore',
                  'Tantramar Marsh','Kouchibouguac','Restigouche River',
                  'Saint John River','Annapolis Valley'],
    'province':  ['NB','NB','NB','NB','NB','NB','NB','NS'],
    'elevation_m':[12, 84, 5, 3, 8, 45, 18, 62],
    'geometry':  [
        Point(-64.96, 46.07), Point(-66.18, 46.85), Point(-65.07, 45.55),
        Point(-64.40, 45.90), Point(-64.95, 46.82), Point(-67.60, 47.70),
        Point(-66.64, 45.95), Point(-65.12, 45.05),
    ],
}
sites = gpd.GeoDataFrame(sites_data, crs='EPSG:4326')

# Protected areas (simplified polygons)
prot_data = {
    'pa_id':    ['PA01','PA02','PA03'],
    'name':     ['Fundy National Park','Kouchibouguac NP','Kejimkujik NP'],
    'type':     ['National Park','National Park','National Park'],
    'area_km2': [207, 239, 404],
    'geometry': [
        Polygon([(-65.4,45.4),(-64.6,45.4),(-64.6,45.7),(-65.4,45.7)]),
        Polygon([(-64.9,46.6),(-64.7,46.6),(-64.7,47.0),(-64.9,47.0)]),
        Polygon([(-65.4,44.5),(-64.8,44.5),(-64.8,44.9),(-65.4,44.9)]),
    ],
}
protected = gpd.GeoDataFrame(prot_data, crs='EPSG:4326')

# Watersheds
ws_data = {
    'ws_id':   ['WS01','WS02','WS03'],
    'name':    ['Saint John Watershed','Miramichi Watershed','Petitcodiac Watershed'],
    'area_km2':[55200, 13800, 3100],
    'geometry':[
        Polygon([(-68.0,46.8),(-66.0,46.8),(-66.0,45.0),(-68.0,45.0)]),
        Polygon([(-66.5,47.5),(-65.5,47.5),(-65.5,46.5),(-66.5,46.5)]),
        Polygon([(-65.2,46.3),(-64.5,46.3),(-64.5,45.7),(-65.2,45.7)]),
    ],
}
watersheds = gpd.GeoDataFrame(ws_data, crs='EPSG:4326')

# Species observations
obs_data = {
    'obs_id':   range(1, 11),
    'species':  ['Atlantic Salmon','Atlantic Salmon','Blanding\'s Turtle',
                 'Piping Plover','Piping Plover','Blanding\'s Turtle',
                 'Atlantic Salmon','Little Brown Bat','Little Brown Bat','Piping Plover'],
    'year':     [2022,2023,2022,2023,2022,2023,2021,2023,2022,2021],
    'count':    [12, 8, 3, 1, 2, 1, 15, 47, 52, 3],
    'geometry': [
        Point(-64.96,46.07), Point(-67.60,47.70), Point(-64.40,45.90),
        Point(-65.07,45.55), Point(-64.95,46.82), Point(-66.18,46.85),
        Point(-66.64,45.95), Point(-66.18,46.85), Point(-64.96,46.07),
        Point(-64.40,45.90),
    ],
}
observations = gpd.GeoDataFrame(obs_data, crs='EPSG:4326')

print("Ecological dataset loaded:")
for name, gdf in [('sites',sites),('protected_areas',protected),
                  ('watersheds',watersheds),('observations',observations)]:
    print(f"  {name:<18s}: {len(gdf)} features, CRS={gdf.crs.to_epsg()}")


print("=== Spatial operations in GeoPandas ===")
print()

# .distance() — element-wise distances
sites_utm = sites.to_crs("EPSG:32620")
s01 = sites_utm[sites_utm.site_id=='S01'].geometry.iloc[0]
distances = sites_utm.geometry.distance(s01)
print("Distances from S01 (Petitcodiac River) in metres:")
for i, (_, row) in enumerate(sites_utm.iterrows()):
    print(f"  {row.site_id} {row.site_name:<24s}  {distances.iloc[i]/1000:.1f} km")

print()
# .buffer(), .union_all(), .intersection()
prot_utm = protected.to_crs("EPSG:32620")

# Buffer and dissolve
buf_5km = prot_utm.copy()
buf_5km['geometry'] = prot_utm.geometry.buffer(5_000)
print(f"Protected areas with 5km buffer (individual):")
for _, row in buf_5km.iterrows():
    print(f"  {row.pa_id}  buffer area = {row.geometry.area/1e6:.0f} km²")

# Union all buffers into one polygon
unioned = buf_5km.geometry.union_all()
print(f"\nUnion of all buffered areas: {unioned.area/1e6:.0f} km² total")

print()
# Overlay operations
print("=== Overlay: intersection and difference ===")
ws_utm = watersheds.to_crs("EPSG:32620")
# Intersection: area of watersheds that overlaps with protected area buffers
prot_buf_gdf = gpd.GeoDataFrame(
    {'name': ['All protected + 5km buffer']},
    geometry=[unioned], crs="EPSG:32620"
)
# Simple overlay demo
for _, ws in ws_utm.iterrows():
    overlap = ws.geometry.intersection(unioned)
    pct = 100 * overlap.area / ws.geometry.area if ws.geometry.area > 0 else 0
    print(f"  {ws['name']:<32s}  protected area overlap: {pct:.1f}%")

print()
print("GeoPandas overlay methods:")
overlay_ops = [
    ("gpd.overlay(a, b, how='intersection')", "Return areas in both a AND b"),
    ("gpd.overlay(a, b, how='union')",        "Return all areas from a and b (merged)"),
    ("gpd.overlay(a, b, how='difference')",   "Return areas in a but NOT in b"),
    ("gpd.overlay(a, b, how='symmetric_difference')", "Areas in a or b but not both"),
    ("gpd.overlay(a, b, how='identity')",     "Everything from a; clipped to b boundaries"),
    ("gpd.sjoin(a, b, predicate='within')",   "Spatial join — attributes from b added to a"),
]
for fn, desc in overlay_ops:
    print(f"  {fn:<48s}  {desc}")


Ecological dataset loaded:
  sites             : 8 features, CRS=4326
  protected_areas   : 3 features, CRS=4326
  watersheds        : 3 features, CRS=4326
  observations      : 10 features, CRS=4326
=== Spatial operations in GeoPandas ===

Distances from S01 (Petitcodiac River) in metres:
  S01 Petitcodiac River         0.0 km
  S02 Miramichi Lake            127.7 km
  S03 Fundy Shore               58.4 km
  S04 Tantramar Marsh           47.3 km
  S05 Kouchibouguac             83.4 km
  S06 Restigouche River         270.9 km
  S07 Saint John River          130.8 km
  S08 Annapolis Valley          114.0 km

Protected areas with 5km buffer (individual):
  PA01  buffer area = 3119 km²
  PA02  buffer area = 1354 km²
  PA03  buffer area = 3112 km²

Union of all buffered areas: 7585 km² total

=== Overlay: intersection and difference ===
  Saint John Watershed              protected area overlap: 0.0%
  Miramichi Watershed               protected area overlap: 0.0%
  Petitcodiac Watershed  

---
## Reading and writing spatial data

In [5]:
print("=== Reading and writing spatial data ===")
print()

import json, tempfile, os

# Write to GeoJSON
tmp = tempfile.NamedTemporaryFile(suffix='.geojson', delete=False)
tmp.close()  # close so geopandas can open and write to it on Windows
sites.to_file(tmp.name, driver='GeoJSON')
print(f"Written to GeoJSON: {tmp.name}")

# Read back
sites_back = gpd.read_file(tmp.name)
print(f"Read back: {len(sites_back)} features, CRS={sites_back.crs}")
os.unlink(tmp.name)

print()
print("Data I/O methods:")
io_methods = [
    ("gpd.read_file('path.geojson')",       "GeoJSON, Shapefile, GeoPackage, KML, ..."),
    ("gpd.read_file('path.gpkg', layer=l)", "Specific layer in GeoPackage"),
    ("gpd.read_postgis(sql, con, geom_col)","Read from PostGIS (requires sqlalchemy)"),
    ("gdf.to_file('output.gpkg', driver='GPKG')", "Write GeoPackage"),
    ("gdf.to_file('output.geojson')",       "Write GeoJSON"),
    ("gdf.to_postgis('table', con, ...)",   "Write to PostGIS"),
    ("gdf.to_wkt()",                        "Convert geometry column to WKT strings"),
    ("gpd.GeoDataFrame.from_wkt(df, col)",  "Build GeoDataFrame from WKT column"),
]
for method, desc in io_methods:
    print(f"  {method:<48s}  {desc}")

print()
print("Read from PostGIS (requires live PostgreSQL + PostGIS):")
print("""
  from sqlalchemy import create_engine
  import geopandas as gpd

  engine = create_engine('postgresql://user:pass@localhost/ecodb')

  gdf = gpd.read_postgis(
      "SELECT site_id, site_name, province, geom FROM monitoring_sites",
      con=engine,
      geom_col='geom',
      crs='EPSG:4326'
  )

  # Write back (after processing):
  gdf.to_postgis('monitoring_sites_processed', engine,
                 if_exists='replace', index=False)
""")

=== Reading and writing spatial data ===

Written to GeoJSON: C:\Users\saman\AppData\Local\Temp\tmpfw0gzmzj.geojson
Read back: 8 features, CRS=EPSG:4326

Data I/O methods:
  gpd.read_file('path.geojson')                     GeoJSON, Shapefile, GeoPackage, KML, ...
  gpd.read_file('path.gpkg', layer=l)               Specific layer in GeoPackage
  gpd.read_postgis(sql, con, geom_col)              Read from PostGIS (requires sqlalchemy)
  gdf.to_file('output.gpkg', driver='GPKG')         Write GeoPackage
  gdf.to_file('output.geojson')                     Write GeoJSON
  gdf.to_postgis('table', con, ...)                 Write to PostGIS
  gdf.to_wkt()                                      Convert geometry column to WKT strings
  gpd.GeoDataFrame.from_wkt(df, col)                Build GeoDataFrame from WKT column

Read from PostGIS (requires live PostgreSQL + PostGIS):

  from sqlalchemy import create_engine
  import geopandas as gpd

  engine = create_engine('postgresql://user:pass@localho

---
## Common Pitfalls

**1. CRS mismatch in spatial operations**
`gdf1.sjoin(gdf2)` when `gdf1.crs == 'EPSG:4326'` and `gdf2.crs == 'EPSG:32620'` raises a `CRSError`. Always verify CRS before spatial operations: `assert gdf1.crs == gdf2.crs`. Use `.to_crs()` to align them.

**2. Distance calculations on EPSG:4326 GeoDataFrames**
`gdf.geometry.distance(other)` on EPSG:4326 returns degrees. Convert to UTM first: `gdf.to_crs('EPSG:32620').geometry.distance(...)`.

**3. `None` CRS on GeoDataFrame construction**
`gpd.GeoDataFrame({'geometry': [Point(0,0)]})` has `crs=None`. Many operations fail silently or raise errors with no CRS. Always set CRS at creation: `crs='EPSG:4326'` argument or `gdf = gdf.set_crs('EPSG:4326')`.

**4. read_file on a Shapefile missing sidecar files**
A Shapefile requires `.shp`, `.dbf`, `.shx` and ideally `.prj` to be present together. Missing `.prj` means CRS is unknown (returns `None`). Missing `.dbf` loses all attributes. Use GeoPackage (`.gpkg`) as a single-file alternative.

**5. Modifying geometry in-place without `.copy()`**
`gdf['geometry'] = gdf.geometry.buffer(0.1)` works, but `gdf2 = gdf; gdf2['geometry'] = ...` also modifies `gdf` (same object). Use `gdf2 = gdf.copy()` before modifying geometry to avoid surprises.

**6. sjoin producing unexpected row counts**
`gpd.sjoin(left, right, how='inner')` multiplies rows when left features match multiple right features. A site within 3 watersheds produces 3 rows. Use `how='left'` to keep all left rows, or aggregate after the join.


---
*sql_methods_library - Samantha McGarrigle*